# Generated by Django 5.1.2 on 2025-01-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question_type',
        ),
    ]
