# Generated by Django 5.1.2 on 2025-01-10 11:51

import assessments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_remove_choice_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='question_type',
            field=models.ForeignKey(default=assessments.models.get_default_question_type, on_delete=django.db.models.deletion.CASCADE, to='assessments.questiontype'),
        ),
    ]
