# Generated by Django 5.1.2 on 2024-12-31 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_users', '0004_role'),
        ('assessments', '0003_alter_category_name_alter_question_role_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_users.role'),
        ),
    ]
